### ISSUE TITLE
Globe.gl with Angular ?

### ISSUE THREAD

**Issue by ClementVaugoyeau** [vasturiano/globe.gl#138]
**Describe the bug**
Hello, I try to use Globe.gl in an Angular component, but I have problem with the DOM render of angular I think. In a classic htlm JavaScript file, the function Globe() is rendered well, but I can't convert this function to a renderable element in Angular. Sorry it's not really a bug, is anyone succeed to import globe.gl with Angular 14 maybe there is a same problem in React ? And thank you for this great library.

**Expected behavior**
The Globe() function is render in the htlm element.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [Firefox]
 - Version: [e.g. 22]

**Comment by dunlavy** [comment]
You can either write a custom directive to manage the data layers or use a service to initialize GlobeGL the typical way.

I'm using imports, too, and not a CDN.

![image](https://user-images.githubusercontent.com/6346817/222029333-b3f231ae-c7a2-40b5-b145-bbfc4e47ccce.png)

It works - don't expect that because you're in Angular there aren't ways to use it:

![image](https://user-images.githubusercontent.com/6346817/222029711-b9e89df3-f505-4240-9c1e-ecbe8f13faee.png)

**Comment by dunlavy** [comment]
But I will say I'm having unexpected behavior in #148.  Furthermore, with imports you could have trouble with build optimizers but for my project we do not engage them (we're not really worried about transit).

**Comment by ClementVaugoyeau** [comment]
Thank you for your response, 
I managed a way around it, but your solution is a lot cleaner than mine, aha.
