### ISSUE TITLE
THREE.WebGLRenderer : useLegacyLights depreciated

### ISSUE THREAD

**Issue by NikooDev** [vasturiano/globe.gl#188]
**Describe the bug**

<img width="1584" alt="Capture d’écran 2024-01-18 à 15 12 54" src="https://github.com/vasturiano/globe.gl/assets/43614012/7f9d6c1e-6294-4137-a38a-f21512965242">

For lighting, you'll need to use custom settings
[https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733](url)

Do you plan to update the globe lighting?

**Comment by vasturiano** [comment]
@NikooDev it is already updated, since `v2.29.0`.
https://github.com/vasturiano/globe.gl/commit/30bbe179d5c43ca1a54595f6bc2a10d75cf2de92

It's forcing it to `false` (modern behavior) in case it encounters an older version of three (before 155), so that it has a consistent behavior. Imo, that warning shouldn't be launched by three when that property is set to `false` (the current default), only when it's set to `true`.

**Comment by LC43** [comment]
hi thanks for the latest updates!
Since the property is actually deprecated, it's triggering the notice because globe.gl is setting it.

**Comment by vasturiano** [comment]
@LC43 we could that, but how does one check the running version of the ThreeJS renderer?

**Comment by vasturiano** [comment]
@LC43 I've made the fix that you suggested. So, the warning should be no more in future versions of globe.gl.

**Comment by LC43** [comment]
thanks @vasturiano ! i confirm the warning is gone, well done!
