### ISSUE TITLE
Polygons on click not triggered with higher altitude

### ISSUE THREAD

**Issue by JohnCoene** [vasturiano/globe.gl#2]
Hi Vasco,

Thanks for the amazing library! 

I seem to have encountered a bug. `onPolygonClick` does not fire when `polygonAltitude` is set to a higher value: at first things appear to work correctly but stop working if the globe has been rotated.

Below is a reproducible example based [on yours](https://github.com/vasturiano/globe.gl/blob/master/example/choropleth-countries/index.html).

```html
<head>
  <style> body { margin: 0; } </style>

  <script src="https://cdn.jsdelivr.net/npm/d3"></script>

  <script src="https://cdn.jsdelivr.net/npm/globe.gl"></script>
  <!--<script src="../../dist/globe.gl.js"></script>-->
</head>

<body>
  <div id="globeViz"></div>

  <script>
    var world;
    const colorScale = d3.scaleSequentialSqrt(d3.interpolateYlOrRd);
    // GDP per capita (avoiding countries with small pop)
    const getVal = feat => feat.properties.GDP_MD_EST / Math.max(1e5, feat.properties.POP_EST);
    fetch('https://raw.githubusercontent.com/vasturiano/globe.gl/master/example/datasets/ne_110m_admin_0_countries.geojson').then(res => res.json()).then(countries =>
    {
      const maxVal = Math.max(...countries.features.map(getVal));
      colorScale.domain([0, maxVal]);
      console.log(countries);
      world = Globe()
        .globeImageUrl('https://cdn.jsdelivr.net/npm/three-globe/example/img/earth-night.jpg')
        .polygonsData(countries.features)
        .polygonAltitude(0.5) // set higher
        .polygonCapColor(feat => colorScale(getVal(feat)))
        .polygonSideColor(() => 'rgba(0, 100, 0, 0.15)')
        .polygonStrokeColor(() => '#111')
        .polygonLabel(({ properties: d }) => `
          <b>${d.ADMIN} (${d.ISO_A2}):</b> <br />
          GDP: <i>${d.GDP_MD_EST}</i> M$<br/>
          Population: <i>${d.POP_EST}</i>
        `)
        .onPolygonClick(hoverD => world // change to on click
          .polygonCapColor(d => d === hoverD ? 'steelblue' : colorScale(getVal(d)))
        )
        .polygonsTransitionDuration(300)
      (document.getElementById('globeViz'))
    });
  </script>
</body>
```

**Comment by vasturiano** [comment]
Hi @JohnCoene, thanks for reaching out.

I've turned your example code into a codepen and it seems to be working for me. Can you try it in the following link and let me know if you still observe your issue:
https://codepen.io/vasturiano/pen/YzKRrjP

I've also added a console log statement at every click, just to be sure.

**Comment by nalbadia** [comment]
Hi, 

I have a similar issue. Try also to perform auto rotate the onclick sometimes fires and sometimes does not. Additionally when I try your codepen example I  get a similar issue after some clicks the polygon get selected. 

Thank you for your kind help

**Comment by vasturiano** [comment]
@nalbadia are you per chance using a trackpad and a 3-finger drag motion to rotate the globe?

By design, the hover/click interactions are disabled while the globe is being rotated. That's intentional as it was too confusing if the two interaction types were firing simultaneously.

What may be happening here is that some pointer devices, like the OSX trackpad lock the click+drag motion for a bit of time after releasing. During this extended time the browser actually thinks the user is still dragging, and therefore the other interactions remain disabled briefly. It's just a coincidence that it roughly matches the inertia of the globe rotation slow-down.

An easy way to test this is to perform the rotation using a regular click+drag interaction and observe if the issue still persists.

A bit more background here: https://apple.stackexchange.com/questions/243151/how-to-speed-up-three-finger-drag-delay-on-release

**Comment by sorxrob** [comment]
Hi @vasturiano , I also noticed this.

So onClick (i.e. onPolygonClick) events only works when autorotate is false or after 3 seconds of no interaction when the globe is manually dragged.

Is there a way to listen to click events even if the globe is still rotating?

Thank you!
