### ISSUE TITLE
Incomplete Typescript definitions (regression in v2.34.0)

### ISSUE THREAD

**Issue by kosmoz** [vasturiano/globe.gl#220]
**Describe the bug**

The `Globe` class declaration does not contain all the methods available. This is after updating the code to the `new` instance creation style.

For example `instance.globeImageUrl(...)` gives a compile error, but `(instance as any).globeImageUrl(...)` works (but you lose type checking).

**To Reproduce**
1. Try to use the library in a Typescript project

**Expected behavior**
All available methods contained in Globe class

**Additional context**
The definitions worked in v2.33.2

**Comment by vasturiano** [comment]
Thanks for the report @kosmoz. I've just issued a patch that fixes the type definitions to include all the available methods. The issue was with the application of `omit` in the new class declaration.

If you upgrade to `2.34.1` you shouldn't see the issue anymore. Please let me know if this fixes it for you.

**Comment by kosmoz** [comment]
Thank you for this fast response! Unfortunately, there is a different problem after upgrading to v2.34.1. I created a repository containing minimal code to reproduce this issue. I hope this helps: https://github.com/kosmoz/globe.gl-typedef-bug-repro

**Comment by vasturiano** [comment]
Thanks @kosmoz for the additional info. I've issued another patch which I believe solves this new issue you mentioned.
Could you please try with `2.34.2`?

**Comment by kosmoz** [comment]
It works now, thanks! :slightly_smiling_face:
