### ISSUE TITLE
How to access the rendered hex polygons?

### ISSUE THREAD

**Issue by ian-whitestone** [vasturiano/globe.gl#76]
I am using the hexed polygons layer to render some shapes within a region. Here is an example:

```javascript
import regions from "./geo-data.json";
import Globe from 'globe.gl';

const globe = new Globe()
  (document.getElementById('globeViz'))
  .hexPolygonsData(regions.features)
  .hexPolygonResolution(1)
  .hexPolygonMargin(0.7)
;
```

<img width="400" alt="CleanShot 2021-12-26 at 14 38 57@2x" src="https://user-images.githubusercontent.com/11096727/147418394-3e85f81e-6e0a-4d01-93a0-452f3155d9b9.png">

I would like to get the coordinates of each hexagon, so that i can emit arcs / particles from them. What would be the best way to do this? I tried looking through the underlying `globe.hexPolygonsData()[0].__threeObj` but am a bit lost with what I should be looking for and how to leverage the BufferAttribute data i can see.

Any points or ideas would be greatly appreciated, thanks in advance!

**Comment by vasturiano** [comment]
@ian-whitestone thanks for reaching out.

I don't think you'll be able to (at least easily) reverse engineer the hex coordinates from the three geometry itself. Those would be already calculated 3D vertex coords.

If you just need the hex coordinates on click event, you can get the coordinates from the click event callback, for example via `onHexPolygonCallback((polygon, event, coords) => ...)`. 

Otherwise if you need the hex coordinates for all the polygons for some custom processing, I'd recommend using the [h3 module](https://github.com/uber/h3-js) for this purpose. You can use the [polyfill](https://github.com/uber/h3-js#module_h3.polyfill) functionality to convert your geojson polygons to hex objects, using the same h3 resolution you pass to globe.gl. That's essentially what this layer uses internally.

**Comment by ian-whitestone** [comment]
Thanks @vasturiano ! I'll give that a shot and close this once I have a working POC to share back.
